{% set name = "bert_score" %}
{% set version = "0.3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ffe5838eac8cdd988b8b1a896af7f49071188c8c011a1ed160d71a9899a2ba4

build:
  number: 0
  entry_points:
    - bert-score=bert_score_cli.score:main
    - bert-score-show=bert_score_cli.visualize:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - numpy
    - packaging >=20.9
    - pandas >=1.0.1
    - python >={{ python_min }}
    - requests
    - pytorch >=1.0.0
    - tqdm >=4.31.1
    - transformers >=3.0.0

test:
  imports:
    - bert_score
    - bert_score_cli
  commands:
    - bert-score --help
    - bert-score-show --help
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/Tiiiger/bert_score
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyTorch implementation of BERT score
  doc_url: https://pypi.org/project/bert-score/
  dev_url: https://github.com/Tiiiger/bert_score

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
